@echo off
echo Renaming Dr. Batra's Dentistree Gallery Images...

rename "GalleryImg1.jpg" "1_treatment_chairside.jpg"
rename "GalleryImg2.jpg" "2_clinic_patient_photo.jpg"
rename "GalleryImg3.jpg" "3_clinic_patient_photo.jpg"
rename "GalleryImg4.jpg" "4_clinic_patient_photo.jpg"
rename "GalleryImg5.jpg" "5_clinic_patient_photo.jpg"
rename "GalleryImg6.jpg" "6_clinic_patient_photo.jpg"
rename "GalleryImg7.jpg" "7_clinic_patient_photo.jpg"
rename "GalleryImg8.jpg" "8_clinic_patient_photo.jpg"
rename "GalleryImg9.jpeg" "9_equipment_opg_xray.jpeg"
rename "GalleryImg10.jpg" "10_clinic_presentation.jpg"
rename "GalleryImg11.jpg" "11_treatment_camp_checkup.jpg"
rename "GalleryImg12.jpg" "12_clinic_patient_photo.jpg"
rename "GalleryImg13.jpg" "13_clinic_awareness_program.jpg"
rename "GalleryImg14.jpg" "14_clinic_staff_meeting.jpg"
rename "GalleryImg15.jpg" "15_treatment_camp_checkup.jpg"
rename "GalleryImg16.jpg" "16_clinic_awareness_program.jpg"
rename "GalleryImg17.jpg" "17_clinic_awareness_program.jpg"
rename "GalleryImg18.jpg" "18_clinic_presentation.jpg"
rename "GalleryImg19.jpg" "19_clinic_presentation.jpg"
rename "GalleryImg20.jpg" "20_treatment_school_camp.jpg"
rename "GalleryImg21.jpg" "21_clinic_group_photo.jpg"
rename "GalleryImg22.jpg" "22_treatment_school_camp.jpg"
rename "GalleryImg23.jpg" "23_treatment_school_camp.jpg"
rename "GalleryImg24.jpeg" "24_equipment_opg_xray.jpeg"
rename "GalleryImg25.jpeg" "25_treatment_intraoral_scanning.jpeg"
rename "GalleryImg26.jpg" "26_equipment_itero_scanner.jpg"
rename "GalleryImg27.jpg" "27_clinic_patient_photo.jpg"
rename "GalleryImg28.jpg" "28_clinic_patient_photo.jpg"
rename "GalleryImg29.JPG" "29_clinic_consultation.JPG"
rename "GalleryImg30.jpg" "30_treatment_chairside.jpg"
rename "GalleryImg31.jpg" "31_clinic_doctors_desk.jpg"
rename "GalleryImg32.jpg" "32_clinic_doctor_portrait.jpg"
rename "GalleryImg33.jpg" "33_clinic_doctor_portrait.jpg"
rename "GalleryImg34.jpg" "34_clinic_patient_photo.jpg"
rename "GalleryImg35.jpg" "35_clinic_patient_photo.jpg"
rename "GalleryImg36.jpg" "36_clinic_patient_photo.jpg"
rename "GalleryImg37.jpg" "37_clinic_patient_photo.jpg"

echo Renaming complete! Check the folder to verify.
pause