name: Generate XML Sitemap

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://drbatrasdentistree.com/ # Change to actual deployment URL
        path-to-root: .

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'chore: Automated sitemap update'
        add: 'sitemap.xml'